name: TP_DevOps

env: 
  PYTHON_VERSION: 3.13

on:
  push:
    branches:
      - "main"
  pull_request: 
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Usando rama ${{ github.ref_name }}
        uses: actions/checkout@v4
      
      - name: Instalando Python version ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Instalando dependencias
        run: pip install -r requirements.txt
      
      - name: Ejecutando tests unitarios
        run: pytest
      